### ISSUE TITLE
Meeting to discuss aggregated reports

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_browser_client#130]
Revisit the aggregation functionality of QSEAD (http://qsead.sead.se/) where a report is generated at different aggregation levels based on the selected filters and items: Issues to discuss:

    What aggregation levels? Sites, dataset (sample groups), samples, analysis entities?
    What data should be included in the report(s)?
    Does backend support for this exist?
    Should it use the final SQL generated from current filters and selections or something else as a source?

**Comment by johanvonboer** [comment]
Note to self (from PB after meeting 2020-06-30): Even though several sites are being aggregated into one singe site report, it should still be clear (somehow) which data in the site report belongs to which site.
