### ISSUE TITLE
Summary stats in result table

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_browser_client#131]
In the BugsCEP equivalent of the result table, you can also get a summary of status for each site, it would be nice to have this functionality in the sead browser as well, example of stats in bugs are:

Samples, abundances, references, countsheets, dates: calendar, radiometric, etc...

@visead Which stats should we include in sead?

**Comment by visead** [comment]
Number of datasets (=countsheets)
Number of samples (=physical samples)
Count of abundance (all samples)
Sum of abundance (all samples)
Dates:
Number of calendar dates (=count records in tbl_relative_dates where tbl_relative_ages.relative_age_type_id=(Calendar date, Calendar date range, Calibrated 14C 2sd age range, Other Age type))
Number of period dates (=count records in tbl_relative_dates where tbl_relative_ages.relative_age_type_id=(*period, Geological*, Pollen Zone, Blytt-Sernander, Oxygen Isotope Stage))
Number of radiometric dates (=count records in tbl_geochronology)

SEAD has other useful data for sites that we might want to expand on this with for non-Bugs sites (e.g. number of features)

**Comment by visead** [comment]
Bumping up this one but in a simplified format:
Add number of selected sites to spreadsheet view
- useful both as information to user and for quality control work for data provider (check numbers against expected numbers)
