### ISSUE TITLE
New viewstate text

### ISSUE THREAD

**Issue by visead** [humlab-sead/sead_browser_client#147]
As viewstates may not persist between versions, warn users about this:
"A viewstate functions as a bookmark that saves your currently selected filters and other user interface settings. Viewstates are public and can be viewed by anyone with the link, so can be used for sharing ideas. Please note that they may not persist between interface versions, and so should not be used in publications. We are working on an alternative system for providing permanent identifiers for filter results."

**Comment by johanvonboer** [comment]
Sorry about taking so long with this! I had completely missed it somehow. An easy fix of course and I've updated the text now.
