### ISSUE TITLE
Filter output: Geographic, karta visas endast delvis

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#244]
När man väljer att visa ”Geographic” istället för ”Overview” och väljer PGC ArticDEM syns bara en del av kartan. Är kartan inte en världskarta? Verkar konstigt att ha en  Dessutom visas flera "Base Layers" och "Data Layers" (nya ritas upp för varje gång man går in under fliken, till slut visas inte "Export"-rutan längre). Det sistnämnda oavsett vilken karta man valt.

![bild](https://user-images.githubusercontent.com/100921064/228180427-e0e83a60-cc1a-4768-9dab-e1327abed862.png)

**Comment by johanvonboer** [comment]
Also adding a notification explaining the situation with the arctic dem map.
