### ISSUE TITLE
Abundances filter visar inga staplar

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#246]
Abundances filter visar inga staplar och hur man än ändrar intervallet påverkas inte Filter outputen. Borde något visas? (Endast detta filter har valts. FUngerar det bara tillsammans med något annat filter?)

![bild](https://user-images.githubusercontent.com/100921064/228535237-04c2d14f-98ed-4ed2-a67d-75141443525b.png)

**Comment by johanvonboer** [comment]
Need more info

**Comment by Maanin00** [comment]
Kan inte återskapa. Stänger
