### ISSUE TITLE
Dendro dating graph remains on screen

### ISSUE THREAD

**Issue by MattiasSealander** [humlab-sead/sead_browser_client#262]
Parts of the dendro dating bar graph remains on screen when moving back to geographic/overview map, i.e. moving back from the site report. See result in image below. This happens only in internal version, not public SuperSEAD browser. 

How to replicate: 
- Go to a dendro site report
- Open the dendro date bar graph
- Click on back button
- Result according to image below

Edit: Added better screen cap. 
Further info: Tested only with Mozilla Firefox browser.

![glitched_graphic](https://user-images.githubusercontent.com/44999648/234784018-5e93efeb-2029-4c0b-a12d-2844d5ce49d0.png)

**Comment by johanvonboer** [comment]
Fixed
