### ISSUE TITLE
Samlingsärende för Tour-tutorial

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#265]
1. Om man inte kör igång touren på startsidan blir det konstigt, dvs om man inte skulle se den i uppe i högra hörnet utan söker och går vidare till en annan sida och sen upptäcker rutan och kör igång så körs touren på den sidan man är på. En lösning skulle kunna vara att när man klickar på ”Start tour” växlar man samtidigt till startsidan. Alternativt att tour-rutan enbart visas på startsidan.

2. Om man klickar någon annanstans än där man ska kan det bli problem. Ex om man klickar på ”export site info” på landningssidan istf "Next" så öppnas en ruta för exporten, som visserligen inte går att komma åt, men om man i det läget klickar "Next" så ligger exportrutan kvar och nästa område  i touren går inte att klicka på. Kanske inget att göra åt, svårt att förhindra att folk klickar på fel ställe.

3. Navigering går bara med mus(?), men lägger man till en Next-knapp går det att använda tangentbordet för att stega igenom touren. (Tex  “Click on the Filters menu to open it, or click Next below.”) Men då får man inte alltid rätt input till nästa steg, så lägger man till Next-knappar måste det kodas mer. Kanske inte värt besväret?

4. Klick på sajten på kartan funkar lite annorlunda är när man inte kör touren. Dvs man kan klicka på kartnålen/markören, i normala fall behöver man klicka på namnet i popup-rutan. Förvirrande eller ok?

**Comment by johanvonboer** [comment]
1. Har fixat detta. Systemet "resettas" nu när man startar en tour oavsett vilket läge man befann sig i tidigare. Kan inte garantera att detta fungerar 100% i alla lägen, men det verkar fungera för mig.

2. Det är tekniskt möjligt att förhindra detta, men kräver mycket jobb. Med tanke på att användaren har ett egenintresse av att fullfölja kursen så tycker jag vi låter det vara som det är tills vidare.

3. Yes. Vi bör antagligen lägga till next-knappar överallt. Min tanke var att tvinga användaren till att interagera med sajten istället för att bara fortsätta klicka på next på ett slentrianmässigt sätt. Men även här ligger det ju samtidigt i användarens egenintresse att fullfölja tutorial på det korrekta sättet då det är för deras egen skull de försöker lära sig systemet.

4. Jag förändrade detta överlag, så det är konsekvent på det sättet att man nu alltid tas direkt till site report när man klickar på en enstaka sajt. D.v.s. inte bara när man kör tutorial. Men jag vet inte om jag gillar det. Det är då inte konsekvent med hur det funkar med ett kluster av sajter... Så jag kanske tar tillbaks den här förändringen, men det är någonting som egentligen är separat från tutorial.

**Comment by Maanin00** [comment]
Stänger detta ärende. Om det blir aktuellt att tillgänglighetsanpassa gränssnittet får vi göra ett nytt ärende för punkt 3.
