### ISSUE TITLE
Export-funktionen under "Overview" fungerar inte

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#276]
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/7a25b48f-3b3e-4cfe-8ba9-119a1a9da451)

När man klickar på "Export" under Overview, visas en dialogruta med texten "Site data export" (se nedan) och en animering. Det går att stänga rutan på [x] men animationen ligger kvar. Försvinner bara om man backar tillbaka till söksidan.

![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/b4ff7c13-5077-4309-bdd2-2a764552973c)

Det borde finnas nåt nerladdningsval, t.ex. som när man klickar på export längre ner på sidan under "Analyses". 
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/ae8eb984-4ea2-49ac-8633-74ced306af8f)

Felet uppstår oavsett vilken site det är, och det uppstår oavsett om det finns få eller många prov. Exempel på de jag testat:
Santa Pola
Ferryland
Apalle

**Comment by johanvonboer** [comment]
Fixat
