### ISSUE TITLE
Domain: Ceramic. Valbara filter innehåller ingen data, ska de verkligen vara valbara då?

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#278]
Bibliography modern är tom.
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/fa083c7f-88f7-4546-a46c-3ef7c7f3f4c5)

Geochronology verkar vara tom. (Eller finns data men så lite att det inte syns?) Är antagligen tom eftersom när man ändrar i intervallet så att filtret aktiveras, försvinner alla siter på kartan.
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/31f029d5-b712-477a-854c-0576183c6b6a)

**Comment by johanvonboer** [comment]
Nej, i mitt tycke borde de inte vara valbara. Jag har tagit bort dessa filter från ceramic-domänen i dev.
