### ISSUE TITLE
Domain Ceramic. Sampling context-filtret gör annorlunda gruppering på kartan

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#279]
Startläge: 
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/552f7722-6b9c-42b6-a2ee-42aa7bd3da72)

En del av output-kartan i defaultläget, dvs endast valt domain och inget i filtret.
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/dc78ef8b-e92d-47ec-bc57-5b1d5e25b6b9)

Samma del av output-kartan efter att man valt "Ceramics" i "Sampling context". Nu har grupperingen förändrats. Ingen förändring i vilka sajter som visas, bara grupperingen som är annorlunda. (Ingen zoomnivå har ändrats.)
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/fc124034-d803-476d-bfde-4e9dbc8fbc29)

Inget direkt fel alltså, bara lite skumt beteende.

**Comment by johanvonboer** [comment]
Verkar bero på att servern skickar resultaten i olika ordning beroende på vilken domän man har valt, vilket resulterar i en annan sorteringsordning även på kartan (vilket syns ifall man väljer Geographic => Data layers => Individual). Detta förklarar fortfarande inte varför OpenLayers gör en annan gruppering på punkterna beroende på sorteringsordningen, men det verkar i alla fall vara orsaken och skulle därmed kunna lösas genom att resultaten sorteras, antingen på servern innan de skickas eller i klienten.

**Comment by johanvonboer** [comment]
Tog bort 'sampling context'-filtret från ceramics domänen eftersom det är meningslöst i sammanhanget.
