### ISSUE TITLE
Exportfiler för "Spreadsheet" innehåller inte förväntat data

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#280]
Startläge:
<img src="https://github.com/humlab-sead/sead_browser_client/assets/100921064/d753e716-9096-4ed3-826e-2d1c33f0c82c)" width="300" >
Sen väljs Filter output -> Spreadsheet -> ![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/8e3ee1db-2ebc-4146-a10a-1f71ea473fc2)
.
.

CSV-filen innehåller bara site-id:
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/8f179643-f697-4fd0-b25d-4da49c81e326)

XLSX-Filen innehåller också bara site-id:
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/c7e11bca-da9e-4728-ad14-6781d9048afe)

JSON-filen innehåller inte heller något mer än site-id:
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/33e96456-588d-4b3c-8078-689f78da3bda)

Förväntar mig site-namn och koordinater eftersom de rubrikerna finns. Borde även record type och provdata finnas med?

**Comment by Maanin00** [comment]
Provat i både Chrome och Firefox (samt startat om browser). Testat med olika filter och helt utan något filter alls, samt ett par olika domäner. Samma fel i alla lägen.

**Comment by johanvonboer** [comment]
Fixat i dev, dock utan koordinater då de inte finns tillgängliga i den här vyn, istället kommer det se ut så här:
![image](https://github.com/humlab-sead/sead_browser_client/assets/34707290/37236982-d91e-4e16-803b-00737677f07e)
