### ISSUE TITLE
Implement support for Thermoluminescence analysis method

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_browser_client#292]
One example of it is available here: https://supersead.humlab.umu.se/site/2695

**Comment by johanvonboer** [comment]
@visead Using analysis_entity_id 145008 as an example, I can't find anything connected to it in the database. None of the tables that have analysis_entity_id as a foreign key contains any data related to this.

We have 47 datasets of this type. The data type is specified as 'Undefined other'. Beyond that I can't find anything else about it.

What to do?

**Comment by Ershad-UMU** [comment]
<img width="1684" alt="Screenshot 2023-08-10 121419" src="https://github.com/humlab-sead/sead_browser_client/assets/122025323/0811c91e-814e-4c36-93fd-e18e7bb63b65">

**Comment by johanvonboer** [comment]
Thank you @Ershad-UMU! Don't know how I missed that table. Now I can start implementing this.

**Comment by johanvonboer** [comment]
Fixed
