### ISSUE TITLE
Export från Site map i Overview innehåller konstiga tecken (fel teckenkodning?)

### ISSUE THREAD

**Issue by Maanin00** [humlab-sead/sead_browser_client#300]
En export-csv från Site map ser ut så här:
![bild](https://github.com/humlab-sead/sead_browser_client/assets/100921064/1619c33f-dbbe-463f-abaa-6dbdb92f74bb)

Dvs innehåller inte rätt visning av diakritiska tecken (åäö osv). Ser likadant ut när filen öppnas i Excel. Exporten gjord från domänen Geoarchaeology, men det är samma sak vid export från General.

**Comment by johanvonboer** [comment]
Fixat
